#!/usr/bin/env ansible-playbook -f 50
---
# This playbook requires the following variables:
#   hosts - this is the host(s) that you are trying to run on. any host in the hosts file is valid
#
# Author: Mike Dorman <mdorman@godaddy.com>
#
# Usage: 
#   ansible-playbook disable-glance-quota.yaml -k -K --extra-vars "hosts=glance-servers"

- hosts: '{{ hosts }}'
  sudo: yes
  tasks:
  - include: ../tasks/turn-off-glance-quota.yaml
