#!/usr/bin/env ansible-playbook --forks 50
---
#
# This playbook supports the following variables:
#
# Author: Kris Lindgren <klindgren@godaddy.com>
#
# hosts - host(s)/group(s) on which to run this playbook (REQUIRED)
#
# Example:
#   To run without changing the plabook with differnt uuids run ansible-plabook with the following:
#   ansible-playbook run-puppet.yaml -k -K --extra-vars "hosts=compute-servers"
#

- hosts: '{{ hosts }}'
  sudo: yes
  tasks:
  - include: /etc/ansible/playbooks/tasks/orphaned-vms.yaml
